### ISSUE TITLE
Not picking up correct stage

### ISSUE THREAD

**Issue by mancvso** [matt-filion/s3-db#24]
If I invoke locally

```
sls invoke local -s produccion -f Some
```

I get

```
{ db: 
   { name: 's3-db',
     environment: '$LATEST',
     namePattern: '${db.name}.${db.environment}-${name}' },
  provider: { name: 'aws-s3', region: 'us-west-2' },
  collections: { default: {} },
  serializer: {} }
```

Which later gives me an `InvalidBucketName` exception.

My workaround was setting `STAGE=mystage` on command line but I'm curious on how it will behave on deploy.

**Comment by matt-filion** [comment]
Looks like db.stage should be set to my-stage, or within your serverless.yaml file set an environmetn value for stage.
