### ISSUE TITLE
Fix readme 😁

### ISSUE THREAD

**Issue by davidroman0O** [matt-filion/s3-db#28]
Hi @matt-filion 

👋 

You missed a letter for `database. getColletion` instead `database.getCollection` ! (the "c" letter)

3 times at the end of `readme.md` 

Have a nice day, thx for s3-db 😃

**Comment by matt-filion** [comment]
Thanks for using it! I'll get those fixes taken care of soon :-)

**Comment by matt-filion** [comment]
Resolved.
